apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-app0argo
spec:
  selector:
    matchLabels:
      app: demo-app0argo
  replicas: 3
  template:
    metadata:
      labels:
        app: demo-app0argo
    spec:
      containers:
      - name: demo-app0argo
        image: nanajanashia/argocd-app:1.2
        ports:
        - containerPort: 8080
