apiVersion: apps/v1
kind: Deployment
metadata:
  name: mydep
spec:
  selector:
    matchLabels:
      app: mydep
  replicas: 2
  template:
    metadata:
      labels:
        app: mydep
    spec:
      containers:
      - name: mydep
        image: nanajanashia/argocd-app:1.2
        ports:
        - containerPort: 8080
