apiVersion: apps/v1
kind: Deployment
metadata:
  name: helldeploy
spec:
  selector:
    matchLabels:
      app: helldeploy
  replicas: 3
  template:
    metadata:
      labels:
        app: helldeploy
    spec:
      containers:
      - name: helldeploy
        image: nanajanashia/argocd-app:1.2
        ports:
        - containerPort: 8080
