apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-argo-deployment
spec:
  selector:
    matchLabels:
      app: test-argo-deployment
  replicas: 3
  template:
    metadata:
      labels:
        app: test-argo-deployment
    spec:
      containers:
      - name: test-argo-deployment
        image: nanajanashia/argocd-app:1.2
        ports:
        - containerPort: 8080
