apiVersion: apps/v1
kind: Deployment
metadata:
  name: mydeployhahaha
spec:
  selector:
    matchLabels:
      app: mydeployhahaha
  replicas: 3
  template:
    metadata:
      labels:
        app: mydeployhahaha
    spec:
      containers:
      - name: mydeployhahaha
        image: nanajanashia/argocd-app:1.2
        ports:
        - containerPort: 8080
